name: win_dev
dependencies:
  - python=3.12
  - notebook
  - pandas
  - numpy
  - scikit-learn
  - matplotlib
  - seaborn
  - xgboost
  - lifelines
  - statsmodels
  - pycatch22
  - umap-learn
  - scipy
  - hdbscan
  - plotly
  - networkx
  - keras
  - pytorch
  - torchvision 
  - torchaudio 
  - pytorch-cuda=12.4
  - spyder